server:
  port: 9411
spring:
  application:
    name: zipkin-server-mysql
  datasource:
      url: jdbc:mysql://localhost:3306/zipkin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
zipkin:
  storage:
    type: mysql