server:
  port: 8085
spring:
  application:
    name: zipkin-client
  sleuth:
    sampler:
      percentage: 1
#      probability: 1
  zipkin:
    baseUrl: http://localhost:9411
#logging:
#  level:
#    root: info